version: '3'
services:
  node-app:
    container_name: serverNode
    build: .
    depends_on: 
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:3000" # Puedes cambiar el puerto si es necesario
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  mongo:
    image: mongo
    container_name: serverMongo
    ports:
      - "27017:27017" # Puedes cambiar el puerto si es necesario